# Data Visualization Using `plotnine`

The Palmer Penguins dataset had a variety of column types with which to explore some nice visualizations. The `mtcars` dataset is another popular dataset for doing some simple data work, but does not contain the same types of variables.

Run the following code to load the `mtcars` dataset and explore the observations and variables contained within. To learn more about this dataset check out [this site](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

In [1]:
import statsmodels.api as sm
import pandas as pd

mtcars = sm.datasets.get_rdataset("mtcars", "datasets", cache=True).data
df = pd.DataFrame(mtcars)

In [2]:
df

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
rownames,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

The statement "the `mtcars` dataset does not contain the same types of variables as the penguins dataset" is a little true and a little false. There are no variables that contain text values, BUT there are variables that it makes sense to consider categorical variables. In most situations, it makes sense to treat the values of categorical variables as text values instead of numeric values.

Use the `astype()` method to convert the categorical variables of the `mtcars` (df) dataset to have text values in the code chunk below. We've done one for you!

In [3]:
df["am"] = df["am"].astype(str)

# Convert the other variables below

df["vs"] = df["vs"].astype(str)
df["cyl"] = df["cyl"].astype(str)

In [4]:
print(df)

                      mpg cyl   disp   hp  drat     wt   qsec vs am  gear  \
rownames
Mazda RX4            21.0   6  160.0  110  3.90  2.620  16.46  0  1     4
Mazda RX4 Wag        21.0   6  160.0  110  3.90  2.875  17.02  0  1     4
Datsun 710           22.8   4  108.0   93  3.85  2.320  18.61  1  1     4
Hornet 4 Drive       21.4   6  258.0  110  3.08  3.215  19.44  1  0     3
Hornet Sportabout    18.7   8  360.0  175  3.15  3.440  17.02  0  0     3
Valiant              18.1   6  225.0  105  2.76  3.460  20.22  1  0     3
Duster 360           14.3   8  360.0  245  3.21  3.570  15.84  0  0     3
Merc 240D            24.4   4  146.7   62  3.69  3.190  20.00  1  0     4
Merc 230             22.8   4  140.8   95  3.92  3.150  22.90  1  0     4
Merc 280             19.2   6  167.6  123  3.92  3.440  18.30  1  0     4
Merc 280C            17.8   6  167.6  123  3.92  3.440  18.90  1  0     4
Merc 450SE           16.4   8  275.8  180  3.07  4.070  17.40  0  0     3
Merc 450SL           17.3   8  275.8  180  3.07  3.730  17.60  0  0     3
Merc 450SLC          15.2   8  275.8  180  3.07  3.780  18.00  0  0     3
Cadillac Fleetwood   10.4   8  472.0  205  2.93  5.250  17.98  0  0     3
Lincoln Continental  10.4   8  460.0  215  3.00  5.424  17.82  0  0     3
Chrysler Imperial    14.7   8  440.0  230  3.23  5.345  17.42  0  0     3
Fiat 128             32.4   4   78.7   66  4.08  2.200  19.47  1  1     4
Honda Civic          30.4   4   75.7   52  4.93  1.615  18.52  1  1     4
Toyota Corolla       33.9   4   71.1   65  4.22  1.835  19.90  1  1     4
Toyota Corona        21.5   4  120.1   97  3.70  2.465  20.01  1  0     3
Dodge Challenger     15.5   8  318.0  150  2.76  3.520  16.87  0  0     3
AMC Javelin          15.2   8  304.0  150  3.15  3.435  17.30  0  0     3
Camaro Z28           13.3   8  350.0  245  3.73  3.840  15.41  0  0     3
Pontiac Firebird     19.2   8  400.0  175  3.08  3.845  17.05  0  0     3
Fiat X1-9            27.3   4   79.0   66  4.08  1.935  18.90  1  1     4
Porsche 914-2        26.0   4  120.3   91  4.43  2.140  16.70  0  1     5
Lotus Europa         30.4   4   95.1  113  3.77  1.513  16.90  1  1     5
Ford Pantera L       15.8   8  351.0  264  4.22  3.170  14.50  0  1     5
Ferrari Dino         19.7   6  145.0  175  3.62  2.770  15.50  0  1     5
Maserati Bora        15.0   8  301.0  335  3.54  3.570  14.60  0  1     5
Volvo 142E           21.4   4  121.0  109  4.11  2.780  18.60  1  1     4

                     carb
rownames
Mazda RX4               4
Mazda RX4 Wag           4
Datsun 710              1
Hornet 4 Drive          1
Hornet Sportabout       2
Valiant                 1
Duster 360              4
Merc 240D               2
Merc 230                2
Merc 280                4
Merc 280C               4
Merc 450SE              3
Merc 450SL              3
Merc 450SLC             3
Cadillac Fleetwood      4
Lincoln Continental     4
Chrysler Imperial       4
Fiat 128                1
Honda Civic             2
Toyota Corolla          1
Toyota Corona           1
Dodge Challenger        2
AMC Javelin             2
Camaro Z28              4
Pontiac Firebird        2
Fiat X1-9               1
Porsche 914-2           2
Lotus Europa            2
Ford Pantera L          4
Ferrari Dino            6
Maserati Bora           8
Volvo 142E              2

If you print out your new dataset, is it clear that the variables have been converted to text values? If so, how can you tell?

It should also be clear by how `plotnine` treats these variables.

1. Create side-by-side boxplots of the `mpg` variable by the different values of the `am` variable. What happens if you convert the `am` variable back to float values and then try to create this same plot? Explain the differences between the two plots.

2. Create overlaid histograms of the `hp` variable for the different values of the `cyl` variable. What happens if you convert the `cyl` variable back to float values and then try to create this same plot? Explain the differences between the two plots.

In [5]:
# Create plot for (1) here
from plotnine import ggplot, geom_point, aes, geom_boxplot, geom_boxplot, labs, geom_histogram, theme_light, scale_fill_manual


# Create the boxplot
plot = (
    ggplot(mtcars, aes(x='factor(am)', y='mpg', fill = "am")) +
    geom_boxplot() +
    labs(x='Transmission (0=Automatic, 1=Manual)', y='Miles Per Gallon (mpg)', title='MPG by Transmission Type')
)

plot

# If am is swithced back to float values, the x axis will be adjusted to show the values as continous rather than discrete. For example, if you put a # in front where it would normally be a categorical variable, the colors are not seperate. Instead it turns into a gradient which probably isn't the best option.

ModuleNotFoundError: No module named 'plotnine'

In [ ]:
# Create plot for (2) here

plot = (
    ggplot(mtcars, aes(x='factor(cyl)', y='hp', fill = "cyl")) +
    geom_boxplot() +
    labs(x='Cylinders (cyl)', y='Horsepower (hp)', title='HP by Amount of Cylinders')
)

plot

# If cyl is swithced back to float values, the x axis will be adjusted to show the values as continous rather than discrete. For example, if you put a # in front where it would normally be a categorical variable, the colors are not seperate. Instead it turns into a gradient which probably isn't the best option.

In [ ]:

plot_int_cyl = (
    ggplot(mtcars, aes(x='hp', fill='factor(cyl)')) +
    geom_histogram(position="identity", alpha=0.5, bins=30) +
    labs(x='Horsepower (hp)', y='Count', fill='Cylinders', title='Overlaid Histograms of hp by cyl (integer)') +
    theme_light() +
    scale_fill_manual(values=["red", "green", "blue"])
)

plot_int_cyl

Some of these variables, like the `cyl` variable, have numeric values that actually make sense as numbers (i.e. the number of cylinders in the engine). However, it doesn't make the most sense to "do math" with this type of variable (e.g. take averages and such) because there are so few different value this can take on AND they're an explicit choice made by the car manufacturer. So, it makes more sense to treat the `cyl` variable as a categorical variable despite it having numeric values.

You will need to keep these kinds of nuances about data in mind as you work with an increasing variety and richness of data, and do more complex things with them.

Choose 3 new `geometries` from the [data-to-viz website](https://www.data-to-viz.com/) for graphs that you'd like to explore using the `mtcars` dataset, and then create those graphs!

In [ ]:
# Create plot with first new geometry here
# Converting #2 into a scatterplot, could be a better visual instead of overlaid histogram

from plotnine import scale_color_manual

plot_scatter = (
    ggplot(mtcars, aes(x='hp', y='mpg', color='factor(cyl)')) +
    geom_point() +
    labs(x='Horsepower (hp)', y='Miles per Gallon (mpg)', color='Cylinders', title='Scatterplot of mpg vs. hp colored by cyl') +
    theme_light()
)

plot_scatter

In [ ]:
# Create plot with second new geometry here
# Turning #1 into a density plot to show another visualization that may better represent each transmission type
# chat gpt assisted with the geom_density for transparency so that you can see both graphs even when overlaid
from plotnine import geom_density

plot_density = (
    ggplot(mtcars, aes(x='mpg', fill='factor(am)')) +
    geom_density(alpha=0.5) +
    labs(x='Miles Per Gallon (mpg)', y='Density', fill='Transmission (0=Automatic, 1=Manual)', title='Density Plot of MPG by Transmission Type') +
    theme_light() +
    scale_fill_manual(values=["red", "blue"])
)

plot_density

In [11]:
# Create plot with third new geometry here
# creating my own visual with different variables

from plotnine import geom_area, theme_light

# Sorting the data by 'wt'
mtcars_sorted = mtcars.sort_values(by='wt')

# Creating the area chart comparing wt & qsec
area_chart = (
    ggplot(mtcars_sorted, aes(x='wt', y='qsec'))
    + geom_area(fill='lightblue')
    + theme_light()
)

area_chart

ModuleNotFoundError: No module named 'plotnine'